# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{grammoire}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{moonpxi}]
  s.date = %q{2012-04-28}
  s.description = %q{A context-sensitive grammar library for producing randomised objects}
  s.email = %q{paulo.schneider@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "examples/features/conditions.rb",
    "examples/features/custom_context.rb",
    "examples/features/data_points.rb",
    "examples/features/probability.rb",
    "examples/features/single_rule.rb",
    "grammoire.gemspec",
    "lib/grammoire.rb",
    "lib/grammoire/evaluation_context.rb",
    "lib/grammoire/grammar.rb",
    "lib/grammoire/rule.rb",
    "lib/grammoire/rule_chooser.rb",
    "lib/grammoire/util/random_generator.rb",
    "spec/grammoire/evaluation_context_spec.rb",
    "spec/grammoire/grammar_spec.rb",
    "spec/grammoire/rule_chooser_spec.rb",
    "spec/grammoire/rule_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/moonpxi/grammoire}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{A context-sensitive grammar library for producing randomised objects}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

